# Generated by Django 4.1.7 on 2023-03-01 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+998********'. Up to 15 digits allowed.", regex='^\\+?998?\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='who',
            field=models.CharField(choices=[('Diller', 'Diller'), ('Client', 'Client')], default=('Diller', 'Diller'), max_length=15),
        ),
    ]
