# Generated by Django 4.1.7 on 2023-03-01 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0003_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+998********'. Up to 12w digits allowed.", regex='^\\+?998?\\d{9}$')]),
        ),
    ]
