# Generated by Django 4.1.7 on 2023-02-28 14:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+998********'. Up to 15 digits allowed.", regex='^\\+?998?\\d{9}$')])),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ishlab_chiqarilgan_sana', models.DateField()),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulots',
            },
        ),
        migrations.CreateModel(
            name='Zavod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+998********'. Up to 15 digits allowed.", regex='^\\+?998?\\d{9}$')])),
            ],
            options={
                'verbose_name': 'Zavod',
                'verbose_name_plural': 'Zavodlar',
            },
        ),
        migrations.CreateModel(
            name='Tarqatish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahsulot_soni', models.FloatField()),
                ('tarqatgan_vaqti', models.DateField(auto_now=True)),
                ('bitta_mahsulot_narxi', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_to_tarqatish', to='main.client')),
                ('mahsulot_nomi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahsulot_to_tarqatish', to='main.mahsulot')),
            ],
            options={
                'verbose_name': 'Tarqatish',
                'verbose_name_plural': 'Tarqatishlar',
            },
        ),
        migrations.CreateModel(
            name='OlganMahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahsulot_soni', models.FloatField()),
                ('bitta_mahsulot_narxi', models.FloatField()),
                ('olgan_vaqt', models.DateField(auto_now=True)),
                ('mahsulot_nomi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahsulot_to_olganmahsulot', to='main.mahsulot')),
                ('zavod_nomi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zavod_to_olganmahsulot', to='main.zavod')),
            ],
            options={
                'verbose_name': 'OlganMahsulot',
                'verbose_name_plural': 'OlganMahsulotlar',
            },
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='ishlab_chiqarilgan_korxona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ishlab_chiqarilgan_korxona', to='main.zavod'),
        ),
        migrations.CreateModel(
            name='ClientQarzlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahsulot_soni', models.FloatField()),
                ('bitta_mahsulot_narxi', models.FloatField()),
                ('qarz_berish_vaqti', models.DateField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_to_clientqarzlari', to='main.client')),
                ('mahsulot_nomi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahsulot_nomi_to_clientqarzlari', to='main.client')),
            ],
            options={
                'verbose_name': 'ClientQarzlari',
                'verbose_name_plural': 'ClientQarzlari',
            },
        ),
    ]
