# Generated by Django 4.1.7 on 2023-03-01 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_zavod_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zavod',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+998********'. Up to 12 digits allowed.", regex='^\\+?998?\\d{9}$')]),
        ),
    ]
