# Generated by Django 4.1.7 on 2023-03-01 12:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_alter_client_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+998********'. Up to 12 digits allowed.", regex='^\\+?998?\\d{9}$')])),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Director',
            },
        ),
        migrations.AddField(
            model_name='zavod',
            name='diller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='diller', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zavod',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='zavod',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director', to='main.director'),
        ),
    ]
