# Generated by Django 4.1.7 on 2023-03-01 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_director_zavod_diller_alter_zavod_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='diller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='diller_director', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zavod',
            name='diller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diller_zavod', to=settings.AUTH_USER_MODEL),
        ),
    ]
