# Generated by Django 4.1.7 on 2023-03-01 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_remove_zavod_director_delete_director'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clientlar'},
        ),
        migrations.AlterModelOptions(
            name='mahsulot',
            options={'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='diller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='diller_mahsulot', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
