# Generated by Django 4.1.7 on 2023-03-01 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_client_diller'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OlganMahsulot',
            new_name='ZavoddanOlganMahsulot',
        ),
    ]
