# Generated by Django 4.1.7 on 2023-03-01 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_rename_olganmahsulot_zavoddanolganmahsulot'),
    ]

    operations = [
        migrations.AddField(
            model_name='zavoddanolganmahsulot',
            name='diller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='diller_zavoddanolganmahsulot', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
