# Generated by Django 4.1.7 on 2023-03-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_clientqarzlari_diller_tarqatish_diller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zavoddanolganmahsulot',
            name='olgan_vaqt',
            field=models.DateField(),
        ),
    ]
