# Generated by Django 4.1.7 on 2023-03-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_zavoddanolganmahsulot_olgan_vaqt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientqarzlari',
            name='qarz_berish_vaqti',
            field=models.DateField(),
        ),
    ]
