# Generated by Django 4.1.7 on 2023-03-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_clientqarzlari_qarz_berish_vaqti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarqatish',
            name='tarqatgan_vaqti',
            field=models.DateField(),
        ),
    ]
