# Generated by Django 4.1.7 on 2023-03-02 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_alter_tarqatish_tarqatgan_vaqti'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ombor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahsulot_soni', models.FloatField()),
                ('bitta_mahsulot_narxi', models.FloatField()),
                ('olgan_vaqt', models.DateField()),
                ('diller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diller_ombor', to=settings.AUTH_USER_MODEL)),
                ('mahsulot_nomi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahsulot_to_olganmahsulot', to='main.mahsulot')),
                ('zavod_nomi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zavod_to_olganmahsulot', to='main.zavod')),
            ],
            options={
                'verbose_name': 'OlganMahsulot',
                'verbose_name_plural': 'OlganMahsulotlar',
            },
        ),
        migrations.DeleteModel(
            name='ZavoddanOlganMahsulot',
        ),
    ]
