# Generated by Django 4.1.7 on 2023-03-02 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_ombor_delete_zavoddanolganmahsulot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarqatish',
            name='mahsulot_nomi',
        ),
        migrations.AddField(
            model_name='tarqatish',
            name='ombor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ombor_to_tarqatish', to='main.ombor'),
            preserve_default=False,
        ),
    ]
