# Generated by Django 4.1.7 on 2023-03-02 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_tarqatish_mahsulot_nomi_tarqatish_ombor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarqatish',
            name='ombor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ombor_to_tarqatish', to='main.ombor'),
        ),
    ]
