# Generated by Django 4.1.7 on 2023-03-02 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0019_alter_tarqatish_ombor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZavoddanOlganMahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahsulot_soni', models.FloatField()),
                ('bitta_mahsulot_narxi', models.FloatField()),
                ('olgan_vaqt', models.DateField()),
                ('diller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diller_zavoddanolganmahsulot', to=settings.AUTH_USER_MODEL)),
                ('mahsulot_nomi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahsulot_to_olganmahsulot', to='main.mahsulot')),
                ('zavod_nomi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zavod_to_olganmahsulot', to='main.zavod')),
            ],
            options={
                'verbose_name': 'OlganMahsulot',
                'verbose_name_plural': 'OlganMahsulotlar',
            },
        ),
        migrations.RemoveField(
            model_name='tarqatish',
            name='ombor',
        ),
        migrations.AddField(
            model_name='tarqatish',
            name='mahsulot_nomi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mahsulot_to_tarqatish', to='main.mahsulot'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Ombor',
        ),
    ]
